// user page config
const ITEMS_PER_PAGE = 9
const categories = [
    {
        name: "radia",
        title: "Radioodbiorniki lampowe",
        subTitle: "Eksponaty radiowe",
        description: "W naszej kolekcji znajdują się radioodbiorniki z różnych zakątków świata, które pokazują różnorodność technologii i stylów projektowania na przestrzeni lat. Znajdziesz tu konstrukcje z lat 20-tych i 30-tych jak również 50-tych a nawet 70-tych XX wieku. Nasze zbiory są  podróżą przez historię radiofonii! ",
        pageTemplate: "./src/templates/radia-template.js",
        listTemplate: "./src/templates/radia-list-template.js",
        image: "../images/category-radia.jpg",
    },
    {
        name: "lampy",
        title: "Lampy elektronowe",
        subTitle: "Eksponaty lampowe",
        description: "Lampy elektronowe to serce radioodbiorników, a także fundament rozwoju elektroniki XX wieku. W naszej kolekcji znajdują się różnorodne typy lamp, od klasycznych triod po złożone heptody. Każda lampa to nie tylko element techniczny, ale również świadectwo epoki, w której powstała.",
        pageTemplate: "./src/templates/radia-template.js",
        listTemplate: "./src/templates/lampy-list-template.js",
        image: "../images/category-lampy.jpg",
    },
    {
        name: "odbiorniki",
        title: "Odbiorniki kryształowe",
        subTitle: "Eksponaty radiowe",
        description: "Odbiorniki kryształkowe to jedne z najwcześniejszych form radioodbiorników, które stanowią ważny element naszej kolekcji. Te proste, ale innowacyjne urządzenia wykorzystywały kryształek galeny do demodulacji sygnałów radiowych, nie wymagając zasilania elektrycznego.",
        pageTemplate: "./src/templates/radia-template.js",
        listTemplate: "./src/templates/radia-list-template.js",
        image: "../images/category-odbiorniki.jpg",
    },
    {
        name: "radiostacje",
        title: "Radiostacje",
        subTitle: "Eksponaty radiowe",
        description: "Radiotechnika znalazła także zastosowanie w wojsku. To już nie eleganckie odbiorniki radiowe a sprzęt nadawczo odbiorczy umożliwiający zapewnienie dwukierunkowej łączności w każdych warunkach także na polu walki. Oczywiście istnieją też cywilne radiostacje eksploatowane np. przez radioamatorów. W naszej kolekcji znajdują się między innymi radiostacje, które były na wyposażeniu Wojska Polskiego.",
        pageTemplate: "./src/templates/radia-template.js",
        listTemplate: "./src/templates/radia-list-template.js",
        image: "../images/category-radiostacje.jpg",
    },
    { 
        name: "czasopisma",
        title: "Literatura",
        subTitle: "Eksponaty bibliograficzne",
        description: "Nasza kolekcja literatury obejmuje szeroki wachlarz materiałów, które są nieocenionym źródłem wiedzy dla miłośników radiotechniki i kolekcjonerów. Od podręczników i specjalistycznych publikacji po reklamy i katalogi producentów – nasza literatura oferuje unikalny wgląd w historię i technologię radiokomunikacji.",
        pageTemplate: "./src/templates/radia-template.js",
        listTemplate: "./src/templates/radia-list-template.js",
        image: "../images/category-czasopisma.jpg",
    },
    { 
        name: "wtyczki",
        title: "Wtyczki",
        subTitle: "Wtyczki do urządzeń radiowych",
        description: "W naszej kolekcji znajdują się różnorodne wtyczki i złącza od urządzeń radiowych, które odzwierciedlają rozwój standardów na przestrzeni lat oraz kraju ich powstania. Od klasycznych wtyczek zasilających i głośnikowych po specjalistyczne złącza antenowe – każda wtyczka ma swoją historię i zastosowanie. ",
        pageTemplate: "./src/templates/radia-template.js",
        listTemplate: "./src/templates/lampy-list-template.js",
        image: "../images/category-wtyczki.jpg",
    },
    { 
        name: "galki",
        title: "Gałki i pokrętła",
        subTitle: "Gałki do urządzeń radiowych",
        description: "Gałki i pokrętła to nieodzowny element każdego radioodbiornika, pełniące zarówno funkcje praktyczne, jak i estetyczne. W naszej kolekcji znajdziesz klasyczne bakelitowe pokrętła oraz eleganckie chromowane gałki. Każda gałka i pokrętło to małe dzieło sztuki, które dodaje charakteru i unikalności każdemu odbiornikowi.",
        pageTemplate: "./src/templates/radia-template.js",
        listTemplate: "./src/templates/lampy-list-template.js",
        image: "../images/category-galki.jpg",
    },
    { 
        name: "skale",
        title: "Skale radiowe",
        subTitle: "Skale do radioodbiorników",
        description: "Skale radiowe to nieodzowny element każdego radioodbiornika, który nie tylko umożliwia precyzyjne strojenie, ale również nadaje urządzeniom wyjątkowego charakteru. Każda skala radiowa to małe dzieło sztuki, które odzwierciedla estetykę i technologię swojej epoki. Zapraszamy do zapoznania się z naszą bogatą kolekcją skal radiowych, które są świadectwem historii i rozwoju radiotechniki.",
        pageTemplate: "./src/templates/radia-template.js",
        listTemplate: "./src/templates/lampy-list-template.js",
        image: "../images/category-skale.jpg",
    },
    { 
        name: "scianki",
        title: "Tylne ścianki",
        subTitle: "Tylne ścianki do radioodbiorników",
        description: "Tylne ścianki od radioodbiorników to często niedoceniane, ale istotne elementy konstrukcji urządzeń. Chronią one wewnętrzne komponenty, a także pełnią funkcję informacyjną, zawierając dane techniczne, schematy oraz instrukcje.",
        pageTemplate: "./src/templates/radia-template.js",
        listTemplate: "./src/templates/lampy-list-template.js",
        image: "../images/category-scianki.jpg",
    },
    { 
        name: "filatelistyka",
        title: "Filatelistyka",
        subTitle: "Eksponaty dodatkowe",
        description: "Radio i jego historia uwiecznione zostały na znaczkach i kartkach pocztowych. Z okazji rocznic i wystaw pojawiały się wydania specjalne opatrzone często datownikiem okolicznościowym. Znaczki stosowane były również do noszenia opłat abonamentowych. Te wszystkie walory znajdują się w naszej kolekcji.",
        pageTemplate: "./src/templates/radia-template.js",
        listTemplate: "./src/templates/lampy-list-template.js",
        image: "../images/category-filatelistyka.jpg",
    },
    { 
        name: "filumenistyka",
        title: "Filumenistyka",
        subTitle: "Eksponaty dodatkowe",
        description: "Radioodbiorniki pojawiły się także na pudełkach z zapałkami. Dziś już mało popularne zapałki odegrały swoją rolę w propagowaniu techniki radiowej. W naszej kolekcji można znaleźć etykiety zapałczane z różnych zakładów produkcyjnych.",
        pageTemplate: "./src/templates/radia-template.js",
        listTemplate: "./src/templates/lampy-list-template.js",
        image: "../images/category-filumenistyka.jpg",
    },
    { 
        name: "medale",
        title: "Medale i odznaczenia",
        subTitle: "Eksponaty dodatkowe",
        description: "Producenci sprzętu radiowego jak i stacje radiowe często reklamują się za pomocą znaczków (przypinek). Z okazji rocznic i ważnych wydarzeń emitowane są medale. W naszej kolekcji znajdują się eksponaty zarówno polskie jak i zagraniczne. Niektóre z nich przyjmują kształt lamp elektronowych, odbiorników radiowych czy fal radiowych.",
        pageTemplate: "./src/templates/radia-template.js",
        listTemplate: "./src/templates/lampy-list-template.js",
        image: "../images/category-medale.jpg",
    },
    { 
        name: "emblematy",
        title: "Emblematy",
        subTitle: "Eksponaty dodatkowe",
        description: "Emblematy na radioodbiornikach to nie tylko znaki rozpoznawcze producentów, ale również elementy, które dodają charakteru każdemu urządzeniu. W naszej kolekcji znajdziesz różnorodne emblematy, które odzwierciedlają ducha swoich czasów. Każdy emblemat opowiada historię marki i jej wkładu w rozwój technologii radiowej.",
        pageTemplate: "./src/templates/radia-template.js",
        listTemplate: "./src/templates/lampy-list-template.js",
        image: "../images/category-emblematy.jpg",
    },
    { 
        name: "varia",
        title: "Varia",
        subTitle: "Eksponaty dodatkowe",
        description: "W naszych zbiorach znajdują się też eksponaty takie ja: rachunki, pokwitowania czy opakowania po lampach elektronowych i odbiornikach. Są tylko luźno związane z techniką radiofonią ale wnoszą wiele wiedzy do udokumentowania rozwoju radiotechniki.",
        pageTemplate: "./src/templates/radia-template.js",
        listTemplate: "./src/templates/lampy-list-template.js",
        image: "../images/category-varia.jpg",
    },
    { 
        name: "konstrukcje",
        title: "Nasze konstrukcje lampowe",
        subTitle: "Eksponaty DIY",
        description: "Oprócz kolekcjonowania historycznych radioodbiorników, prezentujemy również własne konstrukcje lampowe. Nasze projekty łączą klasyczną technologię lamp elektronowych z nowoczesnym podejściem do designu i funkcjonalności.",
        pageTemplate: "./src/templates/radia-template.js",
        listTemplate: "./src/templates/radia-list-template.js",
        image: "../images/category-medale.jpg",
    },
    { 
        name: "mierniki",
        title: "Sprzęt radiotechniczny",
        subTitle: "Eksponaty dodatkowe",
        description: "Technika radiowa to także szereg sprzętu pomocniczego: pomiarowego, diagnostycznego, serwisowego itp. W naszejkolekcji znajdują się: mierniki lamp elektronowych, amperomierze, woltomierze, mierniki uniwersalne, generatory, oscyloskopy.",
        pageTemplate: "./src/templates/radia-template.js",
        listTemplate: "./src/templates/radia-list-template.js",
        image: "../images/category-mierniki.jpg",
    },
]

module.exports = {
    ITEMS_PER_PAGE,
    categories,
};